// Generated by CoffeeScript 1.3.2
var app, assets, express, http, io, moment, port, server, socketio, stylus, twit, twitter;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

http = require('http');

socketio = require('socket.io');

moment = require('moment');

twitter = require('ntwitter');

app = express();

server = http.createServer(app);

io = socketio.listen(server);

server.listen(8000);

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.use(express.favicon());

app.set('view engine', 'jade');

app.get('/', function(req, res) {
  return res.render('index');
});

twit = new twitter({
  consumer_key: 'rlNthyhOMxKjgm4Fu6ou3Q',
  consumer_secret: 'u1OkWvNONtuJT1oo9A0dmkurKe2DdsYQDkpGpANKQ4',
  access_token_key: '502914149-eVsG9cRNfWM5mw6VtPPChafLLNZVss3heiT9X0fQ',
  access_token_secret: 'vUX0OtTOyPlkjPKiHdqb6JtAHNKMfI4MmboVWA'
});

io.sockets.on('connection', function(socket) {
  var emitNews;
  emitNews = function() {
    return socket.emit('time', moment().format('dddd, MMMM Do YYYY, h:mm:ss a'));
  };
  setInterval(emitNews, 1000);
  socket.on('disconnect', function() {
    return clearInterval(emitNews);
  });
  return socket.on('keyword', function(keyword) {
    return twit.stream('statuses/filter', {
      track: keyword
    }, function(stream) {
      stream.on('data', function(data) {
        return socket.emit('tweet', data.text);
      });
      stream.on('end', function(response) {});
      return stream.on('destroy', function(response) {});
    });
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
